import { NextResponse } from 'next/server'

const mockShoppingItems = [
  {
    id: '1',
    userId: 'user1',
    text: 'Молоко',
    quantity: '2',
    isBought: false,
    category: 'food',
    userName: 'Алексей',
    createdAt: '2026-03-04T09:15:10Z',
  },
  {
    id: '2',
    userId: 'user1',
    text: 'Хлеб',
    quantity: '1',
    isBought: true,
    category: 'food',
    userName: 'Алексей',
    createdAt: '2026-03-04T08:00:00Z',
  },
  {
    id: '3',
    userId: 'user1',
    text: 'Картошка',
    quantity: '3 кг',
    isBought: false,
    category: 'food',
    userName: 'Алексей',
    createdAt: '2026-03-04T08:00:01Z',
  },
  {
    id: '4',
    userId: 'user1',
    text: 'Лук',
    quantity: '1 кг',
    isBought: false,
    category: 'food',
    userName: 'Алексей',
    createdAt: '2026-03-04T08:00:02Z',
  },
  {
    id: '5',
    userId: 'user1',
    text: 'Морковь',
    quantity: '1 кг',
    isBought: false,
    category: 'food',
    userName: 'Алексей',
    createdAt: '2026-03-04T08:00:03Z',
  },
  {
    id: '6',
    userId: 'user2',
    text: 'Стиральный порошок',
    quantity: '1',
    isBought: false,
    category: 'household',
    userName: 'Мария',
    createdAt: '2026-03-03T15:00:00Z',
  },
  {
    id: '7',
    userId: 'user2',
    text: 'Средство для мытья посуды',
    quantity: '1',
    isBought: true,
    category: 'household',
    userName: 'Мария',
    createdAt: '2026-03-03T15:00:01Z',
  },
  {
    id: '8',
    userId: 'user3',
    text: 'Батарейки АА',
    quantity: '4',
    isBought: false,
    category: 'other',
    userName: 'Дмитрий',
    createdAt: '2026-03-02T12:00:00Z',
  },
  {
    id: '9',
    userId: 'user1',
    text: 'Яйца',
    quantity: '1 десяток',
    isBought: false,
    category: 'food',
    userName: 'Алексей',
    createdAt: '2026-03-04T08:45:12Z',
  },
  {
    id: '10',
    userId: 'user1',
    text: 'Масло сливочное',
    quantity: '1',
    isBought: true,
    category: 'food',
    userName: 'Алексей',
    createdAt: '2026-03-04T08:45:13Z',
  },
  {
    id: '11',
    userId: 'user2',
    text: 'Мешки для мусора',
    quantity: '1 упаковка',
    isBought: false,
    category: 'household',
    userName: 'Мария',
    createdAt: '2026-03-03T15:00:02Z',
  },
  {
    id: '12',
    userId: 'user3',
    text: 'Свечки для торта',
    quantity: '1 набор',
    isBought: false,
    category: 'other',
    userName: 'Дмитрий',
    createdAt: '2026-03-02T12:00:01Z',
  },
  {
    id: '13',
    userId: 'user1',
    text: 'Сыр',
    quantity: '300г',
    isBought: false,
    category: 'food',
    userName: 'Алексей',
    createdAt: '2026-03-04T10:00:00Z',
  },
  {
    id: '14',
    userId: 'user2',
    text: 'Туалетная бумага',
    quantity: '1 упаковка',
    isBought: false,
    category: 'household',
    userName: 'Мария',
    createdAt: '2026-03-03T15:00:03Z',
  },
  {
    id: '15',
    userId: 'user3',
    text: 'Обёрточная бумага',
    quantity: '1',
    isBought: true,
    category: 'other',
    userName: 'Дмитрий',
    createdAt: '2026-03-02T12:00:02Z',
  },
]

export async function GET() {
  return NextResponse.json(mockShoppingItems)
}
